import { GraphicsItem } from "./GraphicsCarousel";

// IPCS Global graphics
export const ipcsItems: GraphicsItem[] = [
  {
    id: 1,
    title: "Industrial Automation",
    description: "Promotional graphic for Industrial Automation course",
    image: "public/lovable-uploads/dbd97283-009e-4f09-b1ec-8621c7b4b48f.png",
    tags: ["Marketing", "Course Promotion"],
  },
  {
    id: 2,
    title: "Industrial Automation - Package",
    description: "Course package advertisement with salary details",
    image: "public/lovable-uploads/324dc493-18fb-4caf-aeb5-dd9e7938a670.png",
    tags: ["Social Media", "Advertisement"],
  },
  {
    id: 3,
    title: "Building Management System",
    description: "Promotional poster for BMS training program",
    image: "public/lovable-uploads/ba06258e-d905-4f0b-b46a-813924a01aa0.png",
    tags: ["Poster Design", "Technology"],
  },
  {
    id: 4,
    title: "Python & Data Science",
    description: "Training course advertisement for Python & Data Science",
    image: "public/lovable-uploads/ca87af4e-189d-472c-a221-58c031c80bee.png",
    tags: ["Course Promotion", "Tech Education"],
  },
  {
    id: 5,
    title: "Digital Marketing Training",
    description: "Promotional graphic for Digital Marketing course",
    image: "public/lovable-uploads/f50ec255-3074-442e-b8f3-419072106c1c.png",
    tags: ["Marketing", "Education"],
  },
  {
    id: 6,
    title: "Data Analytics & Power BI",
    description: "Course advertisement featuring AI/robotics imagery",
    image: "public/lovable-uploads/d8b85c67-18ba-4dc4-8c8c-c2d6a12a0a8d.png",
    tags: ["Tech Education", "AI"],
  },
  {
    id: 7,
    title: "Digital Marketing Course",
    description: "Vibrant promotional banner for digital marketing training",
    image: "public/lovable-uploads/abc499c4-b77d-4d69-8aed-9a966efd6da5.png",
    tags: ["Social Media", "Marketing"],
  },
];

// Hilarius Ayurveda graphics
export const ayurvedaItems: GraphicsItem[] = [
  {
    id: 1,
    title: "Triphala Churna Product",
    description: "Product showcase with natural ingredients",
    image: "public/lovable-uploads/1d36c359-3759-4e2a-bb0b-36c8b159dc27.png",
    tags: ["Product", "Ingredients"],
  },
  {
    id: 2,
    title: "Benefits of Triphala Churna",
    description: "Comprehensive benefits infographic featuring digestive wellness, stress reduction, and more",
    image: "public/lovable-uploads/068baefb-61dd-498b-9689-7e20687a2a26.png",
    tags: ["Benefits", "Infographic"],
  },
  {
    id: 3,
    title: "Three Pillars of Health",
    description: "Illustrative guide showing key health benefits for GIT, stress, and oral care",
    image: "public/lovable-uploads/ad4e2d26-af10-471c-851d-5d7824212eca.png",
    tags: ["Health", "Wellness"],
  },
  {
    id: 4,
    title: "Goodness Inside",
    description: "Breakdown of key ingredients: Bibhitaki, Amla, and Haritaki",
    image: "public/lovable-uploads/ace1e715-63f0-45f4-bf73-162e5ea24f39.png",
    tags: ["Ingredients", "Benefits"],
  },
  {
    id: 5,
    title: "Tridoshic Rasayan",
    description: "Ayurvedic blend featuring Vata, Pitta, and Kapha balance",
    image: "public/lovable-uploads/5966a169-b925-490e-9251-6f7d09dfbaaa.png",
    tags: ["Ayurveda", "Balance"],
  },
  {
    id: 6,
    title: "How to Consume",
    description: "Usage instructions with dosage guidelines",
    image: "public/lovable-uploads/825ac8c9-5b70-4a10-83d7-50b8af71e337.png",
    tags: ["Instructions", "Usage"],
  },
  {
    id: 7,
    title: "Brand Comparison",
    description: "Quality comparison with other brands",
    image: "public/lovable-uploads/d296d298-7b91-4419-8164-b1258c813ee8.png",
    tags: ["Comparison", "Quality"],
  },
  {
    id: 8,
    title: "Triphala Packaging - Front",
    description: "Product packaging design front view",
    image: "public/lovable-uploads/d7b27404-b4c1-42aa-84ae-966cf2d78c87.png",
    tags: ["Packaging", "Design"],
  },
  {
    id: 9,
    title: "Triphala Packaging - Side",
    description: "Product packaging design side view",
    image: "public/lovable-uploads/fa445783-697e-4199-91f1-ca81c41006f3.png",
    tags: ["Packaging", "Design"],
  },
  {
    id: 10,
    title: "Triphala Packaging - Full",
    description: "Complete product packaging visualization",
    image: "public/lovable-uploads/88a41df1-96d1-41ce-ac79-ab162e0a762c.png",
    tags: ["Packaging", "Design"],
  },
  {
    id: 11,
    title: "Triphala Package - Detail",
    description: "Detailed view of package design",
    image: "public/lovable-uploads/0136d1d5-dd84-43c9-99ed-0901293373c4.png",
    tags: ["Packaging", "Detail"],
  },
  {
    id: 12,
    title: "Triphala Churna Package",
    description: "Final product package design",
    image: "public/lovable-uploads/2466a5fc-4254-4329-9242-3642d44db5c2.png",
    tags: ["Packaging", "Final"],
  }
];

// Krishna Travels graphics
export const travelsItems: GraphicsItem[] = [
  {
    id: 1,
    title: "Lowest Flight Tickets Guaranteed",
    description: "Promotional banner for flight bookings with zero convenience fees",
    image: "public/lovable-uploads/a5a8ab2e-d850-445d-a3d7-d5485cdb7f17.png",
    tags: ["Travel", "Flight Booking"],
  },
  {
    id: 2,
    title: "Travel Agents B2B Portal",
    description: "B2B portal promotion with 1% cashback offer",
    image: "public/lovable-uploads/894c6ae9-8ce7-454b-8a48-00f73b9c5499.png",
    tags: ["B2B", "Agent Portal"],
  },
  {
    id: 3,
    title: "Agent Connect Platform",
    description: "B2B platform for travel agencies featuring 7K+ connected agents",
    image: "public/lovable-uploads/d07c9a41-3e6e-4862-b683-a78bb4ddde7e.png",
    tags: ["Travel Agency", "Platform"],
  },
  {
    id: 4,
    title: "Jaipur to Delhi Flight",
    description: "One-way flight promotion featuring India Gate",
    image: "public/lovable-uploads/94115097-28ad-451b-af8b-4b4b37772a1b.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 5,
    title: "Jaipur to Mumbai Flight",
    description: "One-way flight promotion featuring Mumbai skyline",
    image: "public/lovable-uploads/c8c2d6a9-5148-4d72-9b72-d02f05be5aa3.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 6,
    title: "Jaipur to Bengaluru Flight",
    description: "One-way flight promotion featuring Bengaluru Palace",
    image: "public/lovable-uploads/32ccefb8-d3ae-4ae8-8aa5-85932e6c8384.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 7,
    title: "Jaipur to Hyderabad Flight",
    description: "One-way flight promotion featuring Charminar",
    image: "public/lovable-uploads/f3420b96-3fbc-4113-b416-46bb8611b1da.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 8,
    title: "Jaipur to Kolkata Flight",
    description: "One-way flight promotion featuring Howrah Bridge",
    image: "public/lovable-uploads/1d0c776a-8dfe-478f-92f1-c2512347d7fa.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 9,
    title: "Jaipur to Chennai Flight",
    description: "One-way flight promotion featuring Marina Beach monument",
    image: "public/lovable-uploads/b53a6eee-d993-42ee-b90e-8019f4140001.png",
    tags: ["Flight Route", "Destination"],
  },
  {
    id: 10,
    title: "Thailand Tourism",
    description: "Promotional banner for Thailand tourism package",
    image: "public/lovable-uploads/7f2d435c-35cc-4a12-9c13-e41ac3178549.png",
    tags: ["International", "Tourism"],
  },
];

// Xclusive Vision graphics
export const xclusiveItems: GraphicsItem[] = [
  {
    id: 1,
    title: "Europe Visa Promotion",
    description: "Promotional banner for Schengen visa services",
    image: "public/lovable-uploads/187a2bef-9553-4ce4-82b2-f220de70b31d.png",
    tags: ["Europe", "Visa Services", "Immigration"],
  },
  {
    id: 2,
    title: "USA Visa Services",
    description: "Promotional graphic for B1/B2 USA visa consultation",
    image: "public/lovable-uploads/591aafda-a0d2-4100-bcbf-04d76ed16c84.png",
    tags: ["USA", "B1/B2 Visa", "Immigration"],
  },
  {
    id: 3,
    title: "Visa Cost Coverage",
    description: "Information about visa fees and services provided",
    image: "public/lovable-uploads/5b974771-2b64-46d5-8a3c-a9ba74022a81.png",
    tags: ["Services", "Payment Options"],
  },
  {
    id: 4,
    title: "UK Visa Success Story",
    description: "Client success story showcasing approved UK visa",
    image: "public/lovable-uploads/a152cc3b-fe80-4a49-8995-c8085773193b.png",
    tags: ["Success Story", "UK Visa", "Testimonial"],
  },
  {
    id: 5,
    title: "Canada Immigration",
    description: "Promotional material for Canadian immigration services",
    image: "public/lovable-uploads/584f65df-4a01-4d49-9b16-14b3223ca896.png",
    tags: ["Canada", "Immigration", "Career"],
  },
  {
    id: 6,
    title: "Poland Visa Services",
    description: "Marketing graphic for Poland immigration opportunities",
    image: "public/lovable-uploads/5b088019-4bd5-4405-a68c-ba85d1a07885.png",
    tags: ["Poland", "Europe", "Immigration"],
  },
  {
    id: 7,
    title: "UK Tier-2 Visa Success",
    description: "Client testimonial for successfully obtaining a UK Tier-2 visa",
    image: "public/lovable-uploads/46f4022a-f799-4b46-9266-5821b27b8292.png",
    tags: ["UK", "Tier-2 Visa", "Success Story"],
  },
  {
    id: 8,
    title: "FAQ & Support",
    description: "Interactive Q&A graphic for visa consultations",
    image: "public/lovable-uploads/bb444f8e-5dc3-44bc-85bc-34633135970b.png",
    tags: ["Support", "FAQ", "Consultation"],
  },
  {
    id: 9,
    title: "Visa Success Stories - 1",
    description: "Promotional banner highlighting client success stories",
    image: "public/lovable-uploads/10c817c0-820b-4b87-a27a-1a56a259b3ff.png",
    tags: ["Testimonials", "Success Stories"],
  },
  {
    id: 10,
    title: "Visa Success Stories - 2",
    description: "Detailed client testimonials and immigration success cases",
    image: "public/lovable-uploads/3592f5eb-0253-495b-8e68-8cb3dc39a530.png",
    tags: ["Testimonials", "Success Stories"],
  },
];
