// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yficbvraqgorbmqzotey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmaWNidnJhcWdvcmJtcXpvdGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjkyMjIsImV4cCI6MjA1OTk0NTIyMn0.vSgL9DaiQwcT-vBcoJShf3cXut8P0wmBFLf4OIdLoS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);